// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7+: connection URLs live in prisma.config.ts (not schema.prisma).
    // Use DIRECT_URL for migrations (direct connection, no pgbouncer).
    // Use DATABASE_URL at runtime in PrismaClient (pooler/pgbouncer OK).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
